% clr_global -- Called by WLBrowser
%  Usage
%    clr_global
%

clear global ...
		 x_signal x_noise x_use ...
		 m_doit n noise_type namp slider_id ...
		   filter_type  shrinkage_type signal_name ...
		   fig_hand1  fig_hand2 fig_hand3 nsig ...
		 Data____entries    Data____callbacks ...
		 Signals_entries    Signals_callbacks ...
		 Noise___entries    Noise___callbacks ...
		 Wavelet_entries    Wavelet_callbacks ...
		 Shrink__entries    Shrink__callbacks ...
		 Actions_entries    Actions_callbacks ...
		 menu_ids menu_tags PlotFig Empty_Data HC ...
		 QMF Coarse
clear global ...
		h_wavemenu  h_bellmenu  h_nonmenu  h_thrmenu  ...
		h_noimenu 	 h_nlvmenu 	h_sigmenu 	 
    
    
%   
% Part of WaveLab Version 802
% Built Sunday, October 3, 1999 8:52:27 AM
% This is Copyrighted Material
% For Copying permissions see COPYING.m
% Comments? e-mail wavelab@stat.stanford.edu
%   
    
